name: leads_test
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  flutter_native_splash: ^2.2.16
  intl: ^0.18.0
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#121212"
  image: assets/images/preloader.png
  android_12:
    image: assets/images/preloader.png
    color: "#121212"
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter-reg.ttf
          weight: 400
        - asset: assets/fonts/inter-med.ttf
          weight: 500
        - asset: assets/fonts/inter-bold.ttf
          weight: 700
