name: leads_test
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/preloader.png
  android_12:
    image: assets/images/preloader.png
    color: "#FFFFFF"
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter-reg.tff
          weight: 400
        - asset: assets/fonts/inter-med.tff
          weight: 500
        - asset: assets/fonts/inter-bold.tff
          weight: 700
